name: Provider

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0']
        deps: ['low', 'high']
        include:
          - php-version: '7.3'
        provider:
          - AlgoliaPlaces
          - ArcGISOnline
          - AzureMaps
          - BingMaps
          - Cache
          - Chain
          - FreeGeoIp
          - GeoIP2
          - GeoIPs
          - GeoPlugin
          - GeocodeEarth
          - Geoip
          - Geonames
          - GoogleMaps
          - GoogleMapsPlaces
          - GraphHopper
          - Here
          - HostIp
          - IP2Location
          - IP2LocationBinary
          - IpInfo
          - IpInfoDb
          - Ipstack
          - LocationIQ
          - MapQuest
          - Mapbox
          - Mapzen
          - MaxMind
          - MaxMindBinary
          - Nominatim
          - OpenCage
          - OpenRouteService
          - Pelias
          - Photon
          - PickPoint
          - TomTom
          - Yandex

    name: ${{ matrix.provider }} PHP ${{ matrix.php-version }} (${{ matrix.deps }})

    steps:
    - uses: actions/checkout@v2

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: curl

    - name: Validate composer.json and composer.lock
      working-directory: ./src/Provider/${{ matrix.provider }}
      run: composer validate

    - name: Install dependencies
      if: ${{ matrix.deps == null }}
      working-directory: ./src/Provider/${{ matrix.provider }}
      run: composer update --no-progress --prefer-dist
    - name: Install dependencies (low)
      if: ${{ matrix.deps == 'low' }}
      working-directory: ./src/Provider/${{ matrix.provider }}
      run: composer update --no-progress --prefer-lowest --prefer-stable
    - name: Install dependencies (high)
      if: ${{ matrix.deps == 'high' }}
      working-directory: ./src/Provider/${{ matrix.provider }}
      run: composer update --no-progress

    - name: Run test suite
      working-directory: ./src/Provider/${{ matrix.provider }}
      run: composer run-script test
